### ISSUE TITLE
rename the  cmd to "go-which"

### ISSUE THREAD

**Issue by gedw99** [hairyhenderson/go-which#143]
should we not call the cmd  "go-which", so we do not get name clashes on linux and darwin with the os level "which" binary ?

I am only refering to the cmd, not the golang package - I do not want to break everyone importing this of course.

for example:

```sh
which which
which: shell built-in command
```
then becomes:

```sh
which go-which
/Users/apple/workspace/go/bin/go-which
```

**Comment by hairyhenderson** [comment]
This is intended as a drop-in replacement for `which(1)`, but also it's intended as a drop-in replacement _that you probably shouldn't use._ (see the README)

If someone chooses to `go install` this, or install it in their path some other way, they should expect it to (possibly) supersede the OS's `which`.
